# Generated by Django 4.0.6 on 2022-08-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_battletag'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='battleTag',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='BattleTag',
        ),
    ]
