# Generated by Django 4.0.6 on 2022-08-22 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_shippingaddress_battletag_delete_battletag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='city',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='country',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='postalCode',
        ),
    ]
