# Generated by Django 4.0.6 on 2022-08-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_shippingaddress_address_shippingaddress_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='battleTag',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
