# Generated by Django 4.0.6 on 2022-08-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_order_battletag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='deliveredAt',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='isDelivered',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='isPaid',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='paidAt',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='paymentMethod',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='taxPrice',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='totalPrice',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='user',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='postalCode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
