# Generated by Django 4.1.1 on 2022-11-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_product_amountinstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amountInStock',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
