# Generated by Django 4.1.1 on 2022-11-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_product_amountinstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amountInStock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
